<?php
$escHtml = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$bannerImage1 = $this->themeSettingAsset('banner_image_1');
$bannerImage2 = $this->themeSettingAsset('banner_image_2');
$bannerImage3 = $this->themeSettingAsset('banner_image_3');

$banner_text = $this->themeSetting('banner_text');

$class = ['main-banner'];
?>

<?php if ($bannerImage1 || $bannerImage2 || $bannerImage3) : ?>
    <div class="<?php echo implode(' ', $class); ?>">
        <div class="main-banner__slider">
            <?php if ( $bannerImage1 ) : ?>
                <div class="main-banner__slide" style="background-image: url('<?php echo $this->themeSettingAssetUrl('banner_image_1'); ?>');"></div>
            <?php endif; ?>
            <?php if ( $bannerImage2 ) : ?>
                <div class="main-banner__slide" style="background-image: url('<?php echo $this->themeSettingAssetUrl('banner_image_2'); ?>');"></div>
            <?php endif; ?>
            <?php if ( $bannerImage3 ) : ?>
                <div class="main-banner__slide" style="background-image: url('<?php echo $this->themeSettingAssetUrl('banner_image_3'); ?>');"></div>
            <?php endif; ?>
        </div>
        <div class="main-banner__content">
            <?php if ($banner_text) : ?>
                <p class="main-banner__text">
                    <?php echo $banner_text; ?>
                </p>
            <?php endif; ?>
            <?php echo $this->partial('common/main-header-search', ['id' => 'banner-search', 'site' => $site]); ?>
        </div>
    </div>
<?php endif; ?>
